# Generated by Django 5.0.4 on 2024-05-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='slug')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='logo')),
                ('founding_year', models.CharField(max_length=4, verbose_name='founding year')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='phone number')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'publisher',
                'verbose_name_plural': 'Publishers',
            },
        ),
    ]
